### ISSUE TITLE
Address issue backlog for the Careers website

### ISSUE THREAD

**Issue by ccooper** [taskcluster/scrum#41]
There are a number of outstanding, small issues that we could fix relatively quickly: https://github.com/mozmeao/lumbergh/issues

**Comment by ccooper** [comment]
We don't have admin access to the careers repo yet to link issues directly, so I'm going to list the issues I want to include here and provide estimates.

- [x] [607 - Search in URL is reset on page load in some circumstances](https://github.com/mozmeao/lumbergh/issues/607): 2 story points
- [x] [606 - Update Employee Engagement Survey data on home page](https://github.com/mozmeao/lumbergh/issues/606): 2 story points
- [x] [487 - Remove jquery](https://github.com/mozmeao/lumbergh/issues/487): 5 story points
- [x] [484 - clean up old pages/assets](https://github.com/mozmeao/lumbergh/issues/484): 1 story point
- [x] [453 - add open graph information](https://github.com/mozmeao/lumbergh/issues/453): 3 story points
- [x] [437 - clarify that "life at mozilla" nav link has an external URL](https://github.com/mozmeao/lumbergh/issues/437): 1 story point

**Comment by ccooper** [comment]
Component issues are done. Closing.
